[package]
name = "child"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpu-time = "1.0.0"
once_cell = "1.16.0"
rand = "0.8.5"
sha3 = "0.10.6"
